export const objects = {
  inputDescr: document.getElementById("inputDescr"),
  inputVal: document.getElementById("inputVal"),
  item: document.getElementsByClassName("expenses__input__item"),
  itemDescr: document.getElementsByClassName("expenses__item__description"),
  itemVal: document.getElementsByClassName("expenses__input__item--value"),
  x: document.getElementsByClassName("expenses__item__delete"),
  list: document.getElementsByClassName("expenses__list"),
  warning: document.getElementById("expenses__input__warning"),
  id: 0,
  dps: [],
  btnSave: document.getElementsByClassName("btn__save")[0],
  btnDelete: document.getElementsByClassName("btn__delete")[0],
  btns: document.getElementsByClassName("btn"),
  total: document.getElementById("total__exp"),
  historyList: document.getElementById("navigation__history--list"),
  historyInput: document.getElementById("navigation__history--input"),
};
