export const objects = {
  inputDescr: document.getElementById("inputDescr"),
  inputVal: document.getElementById("inputVal"),
  item: document.getElementsByClassName("expenses__input__item"),
  itemDescr: document.getElementsByClassName("expenses__item__description"),
  itemVal: document.getElementsByClassName("expenses__input__item--value"),
  x: document.getElementsByClassName("expenses__item__delete"),
  list: document.getElementsByClassName("expenses__list"),
  warning: document.getElementById("expenses__input__warning"),
  id: 0,
  dps: [],
  btnHistory: document.getElementsByClassName("btn__history")[0],
  btnSignIn: document.getElementsByClassName("btn__sign-in")[0],
  btnLogIn: document.getElementsByClassName("btn__log-in")[0],
  btnLogOut: document.getElementsByClassName("btn__log-out")[0],
  btns: document.getElementsByClassName("btn"),
  total: document.getElementById("total__exp"),
};
